<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <AssemblyVersion>12.0.0</AssemblyVersion>
    <FileVersion>12.0.0</FileVersion>
    <Authors />
    <Company />  		        
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="ReferencedAssemblies\**" />
    <EmbeddedResource Remove="ReferencedAssemblies\**" />
    <None Remove="ReferencedAssemblies\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Common" Version="12.0.0-rcrc3" />
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0-rcrc3" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configurationpage.html" />
    <EmbeddedResource Include="Configuration\configurationpage.html" />
  </ItemGroup>

</Project>
